apiVersion: v1
kind: Secret
metadata:
  name: quanvo-secret
type: Opaque
data:
  credentials: W2RlZmF1bHRdCmF3c19hY2Nlc3Nfa2V5X2lkID0gQVNJQVZWQzNJVjZBNU1EVVRXR08KYXdzX3NlY3JldF9hY2Nlc3Nfa2V5ID0gNGIrUWZGTFFqTFJ3ZW1QS1RzVXhtcXB0U3hqTlhwRkVoQWxtNUVWWQphd3Nfc2Vzc2lvbl90b2tlbiA9IEZ3b0daWEl2WVhkekVCY2FEQ3BiMm1Cc3lDK2htKzFQVmlMVkFWSjRsM1dhRmtDN1N2WkZUTWUyN2FndjlhZTE3UDUxc3JKY1FadFBkNis5SXRxZG5KY3Y2S3d1TktSVmZNNEJyaU9NT1JEMEZGSC8rSW5tc2xXaUQzTVRTZjF1MFVOYmgwbnNIZDZ2b3ZOZFZjeDhkZllTbGtqVmdNbGZoc2Z6cUI3eE1TQ3pabWJNRzFzT3dwQmhEcC93NVJSd1NRUnJmcTJudU9hOU9mbHZRb3YwRm5zblR2c3dlL3pxQXAzUzdCME5ERGsza3FVT2thWWxxUWZ1UnptWjJYT1dDS3dkN1YvMTBGcHV0c0pZWUF1UW1NRkk3MTlMV09TWmlzV1h2cFBEM3YxYTdBOWJWY3c2cGpRd2xGSWowZjYyM1NqS21iR29Cakl0VDUxR25qV1lRUytaWlk4bGtDMUlpLytodHNNbWc1QjlHdHZxRW93U2Q4YXlOTWdWMDZqQUlmeDZ5YXNU